todo_app/urls.py
from django.urls import path

from todo_app.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskProcessView,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    path(
        "tasks/<int:pk>/process/",
        TaskProcessView.as_view(),
        name="task-process",
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo_app"

todo_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_app.urls", namespace="todo-app"))
]

todo_app/models.py
from django.db import models


class Task(models.Model):
    caption = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", blank=True, related_name="tasks")

    def __str__(self):
        return self.caption


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

todo_app/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View

from todo_app.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.order_by(
        "completed", "-created"
    ).prefetch_related()


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    template_name = "todo_app/task_form.html"
    success_url = reverse_lazy("todo-app:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    template_name = "todo_app/task_form.html"
    success_url = reverse_lazy("todo-app:task-list")


class TaskProcessView(View):
    def post(self, request, pk):
        state = request.POST.get("completed")

        if state == "True":
            Task.objects.filter(pk=pk).update(completed=True)

        if state == "False":
            Task.objects.filter(pk=pk).update(completed=False)

        return redirect("todo-app:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo_app/task_delete.html"
    success_url = reverse_lazy("todo-app:task-list")


class TagListView(generic.ListView):
    model = Tag
    queryset = Tag.objects.order_by("name")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    template_name = "todo_app/tag_form.html"
    success_url = reverse_lazy("todo-app:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "todo_app/tag_form.html"
    success_url = reverse_lazy("todo-app:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo_app/tag_delete.html"
    success_url = reverse_lazy("todo-app:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Todo List</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>
<body>
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}

    </div>
  </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a class="text-decoration-none" href="{% url 'todo-app:task-list' %}">Home</a></li>
  <li class="list-group-item"><a class="text-decoration-none" href="{% url 'todo-app:tag-list' %}">Tags</a></li>
</ul>

templates/todo_app/tag_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ tag.name }}</h1>
  <p>Delete tag?</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url 'todo-app:tag-list' %}">No</a>
</form>
{% endblock %}

templates/todo_app/tag_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

templates/todo_app/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags
    <a class="btn btn-primary float-end" href="{% url 'todo-app:tag-create' %}">Add</a>
  </h1>
  <br>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th class="col-6"><strong>Name</strong></th>
          <th class="col-3"><strong>Update</strong></th>
          <th class="col-3"><strong>Delete</strong></th>
        </tr>
      </thead>
      <tbody>
        {% for tag in tag_list %}
          <tr>
            <td>
              {{ tag.name }}
            </td>
            <td>
              <a class="btn btn-secondary" href="{% url 'todo-app:tag-update' pk=tag.id %}">Update</a>
            </td>
            <td>
              <a class="btn btn-secondary" href="{% url 'todo-app:tag-delete' pk=tag.id %}">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

templates/todo_app/task_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ task.caption }}</h1>
  <p>Delete task?</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url 'todo-app:task-list' %}">No</a>
</form>
{% endblock %}

templates/todo_app/task_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

templates/todo_app/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>TODO list
    <a class="btn btn-primary float-end" href="{% url 'todo-app:task-create' %}">Add task</a>
  </h1>
  <br>

  {% for task in task_list %}
    <p><strong>{{ task.caption }}</strong>
      {% if task.completed %}
        <span class="text-success"><strong>Done</strong></span>
        <form action="{% url 'todo-app:task-process' task.id %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="completed" value="False">
          <button class="btn btn-secondary float-end" type="submit">Undo</button>
        </form>
      {% else %}
        <span class="text-danger"><strong>Not done</strong></span>
        <form action="{% url 'todo-app:task-process' task.id %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="completed" value="True">
          <button class="btn btn-success float-end" type="submit">Complete</button>
        </form>
      {% endif %}
    </p>
    <p>Created {{ task.created }}
      {% if task.deadline %}
        <span class="text-danger">Deadline: {{ task.deadline }}</span>
      {% endif %}
    </p>
    <p class="text-secondary">Tags:
      {% for tag in task.tags.all %}
        {{ tag.name }}
      {% endfor %}

      <a class="text-primary text-decoration-none" href="{% url 'todo-app:task-update' pk=task.id %}">Update</a>
      <a class="text-primary text-decoration-none" href="{% url 'todo-app:task-delete' pk=task.id %}">Delete</a>
    </p>
    <br>
  {% empty %}
    <p>You have no tasks yet</p>
  {% endfor %}

{% endblock %}